"""
Put your custom settings here, not in settings.py

Settings structure:

- settings.py         : Defaults from Django, do not edit
- settings_ansible.py : Generated by Ansible (not committed)
- settings_custom.py  : Your custom project settings, edit this one
"""

# Standard Library
from socket import getfqdn

# Requirements
from dotenv import load_dotenv

# Project
from project.settings_ansible import *


# Load environment variables
load_dotenv(f'{BASE_DIR}/.envrc')

# Applications
INSTALLED_APPS += [
    # Requirements
    'django_bootstrap5',
    'django_filters',
    'django_htmx',
    'django_vite',
    # Project apps
    'boot',
    'invest'
]

MIDDLEWARE += [
    'django_htmx.middleware.HtmxMiddleware'
]

# Static files
STATICFILES_DIRS = [
    BASE_DIR / 'project' / 'static',
]

# Templates
TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [
            BASE_DIR / 'project' / 'templates',
        ],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

# Emails
ADMINS = (('Diego', 'info@grupomss.com'),)
MANAGERS = ADMINS

if not DEBUG:
    fqdn = getfqdn()
    DEFAULT_FROM_EMAIL = 'webmaster@' + fqdn
    SERVER_EMAIL = 'root@' + fqdn

# Authentication
AUTH_USER_MODEL = 'invest.User'
AUTHENTICATION_BACKENDS = ['invest.backends.EmailAuthBackend']
LOGIN_URL = '/login/'
LOGIN_REDIRECT_URL = '/'


# Vite
DJANGO_VITE = {
    'default': {
        'dev_mode': DEBUG,
    },
}

DATE_FORMAT ='d-M-Y'
DATE_INPUT_FORMATS =(
    '%d-%m-%Y', '%d/%m/%Y', '%d/%m/%y', # '2006-10-25', '10/25/2006', '10/25/06'
    '%b %d %Y', '%b %d, %Y',            # 'Oct 25 2006', 'Oct 25, 2006'
    '%d %b %Y', '%d %b, %Y',            # '25 Oct 2006', '25 Oct, 2006'
    '%B %d %Y', '%B %d, %Y',            # 'October 25 2006', 'October 25, 2006'
    '%d %B %Y', '%d %B, %Y',            # '25 October 2006', '25 October, 2006'
)


LANGUAGE_CODE = 'es-es'
TIME_ZONE = 'Europe/Madrid'
USE_L10N = False


if not DEBUG:
    STATICFILES_DIRS.append(BASE_DIR / 'var' / 'build')

# Local settings, these should not be committed
try:
    from .settings_local import *
except ImportError:
    pass


EMAIL_BACKEND = 'django.core.mail.backends.smtp.EmailBackend'
EMAIL_HOST = 'grupomss-com.correoseguro.dinaserver.com' 
EMAIL_PORT = 465 
EMAIL_USE_SSL = True          
EMAIL_USE_TLS = False
EMAIL_HOST_USER = 'info@grupomss.com'  
EMAIL_HOST_PASSWORD = 'WTCd7v0w92$%'
EMAIL_TIMEOUT = 10 

# Configuración de remitente
DEFAULT_FROM_EMAIL = 'info@grupomss.com'  